// TEMPORARY DATA

export let role = "admin";

export const usersData = [
  {
    id: 1,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/firat.jpg",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 2,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 3,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 4,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 5,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 6,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 7,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 8,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 9,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
  {
    id: 10,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    password: "12345678",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationId: "009",
    organizationName: "Ege University",
    address: "Bornova. İzmir",
    role: ["Admin"],
    photo: "/avatar.png",
    email: "john@doe.com",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
  },
];

export const devicesData = [
  {
    id: 1,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 2,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 3,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 4,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 5,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 6,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 7,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 8,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 9,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
  {
    id: 10,
    deviceId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
    details: "2mt hortum, üstten basmalı vs",
  },
];

export const extinguisherData = [
  {
    id: 1,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 2,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 3,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 4,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 5,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 6,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 7,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 8,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 9,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 10,
    extinguisherId: "1234567890",
    serialNumber:"95958478784",
    ownerId:"75",
    ownerName:"XXXX Hospital",
    address: "Bornova İzmir",
    feature: "CO2",
    respPersonId: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
];

//fireCabinetData
//fireDoorData
//fireSprinklerData .....

export const offersData = [
  {
    id: 1,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",
  },

  {
    id: 2,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 3,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 4,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 5,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 6,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 7,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 8,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 9,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
  {
    id: 10,
    offerId: "101",
    providerId: "001",
    providerName: "Ahmet Mehmet",
    providerOrganization:"XXX Yangın Ltd.",
    phone: "+90 232 366 66 66",
    email: "xxx@gmail.com",
    address: "Çiğli/İzmir",
    ownerId: "138",
    ownerName: "HAtice Bilmemne",
    ownerOrganization: "ZZZ Gıda Tekn. Ltd.",
    ownerAddress: "Kemalpaşa/İzmir",
    ownerPhone: "+90 532 888 88 88",
    ownerEmail: "zzz@gmail.com",
    projectLocation: "Kemalpaşa/İzmir",
    projectSize: "2",
    offerDate: "12/12/2023",
    expiryDate: "25/10/2025",
    unitPrice: "63.450,00",
    amount: "126.900,00",
    paymentTerms:["Teslimatta Peşin", "Vadeli"],
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    offerDetails: "8 adet kuru kimyevi yangın tüpü değişimi anahtar teslim fiyat teklifidir.",

  },
];

export const maintenancesData = [
  {
    id: 1,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 2,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 3,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 4,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 5,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 6,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 7,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 8,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 9,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 10,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedById: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    customerId: "5858475",
    customerName:"Ali Abalı",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
];

export const notificationsData = [
  {
    id: 1,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 2,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 3,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 4,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 5,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 5,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 7,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 8,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 9,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 10,
    notificationId: "889",
    userId: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwnerId: "868548",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    id: 1,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 10, 30, 11, 0),
    // end: new Date(2024, 10, 30, 11, 45),
    // create: new Date(2024, 10, 10, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false, 
  },
  {
    id: 2,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 3,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 4,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 5,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 6,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 7,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 8,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 9,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 10,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 11,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },

  {
    id: 12,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 13,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 14,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },

  {
    id: 15,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 16,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 17,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 18,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  {
    id: 19,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },

  {
    id: 20,
    eventId: "001",
    creatorId: "008",
    creatorName: "Harun Gümüş",
    creatorOrganization: "Dokuz Eylül Üniversitesi",
    respPersonId: "123",
    respPersonName: "Abay Adalı",
    respPersonOrg: "Yaşar Üniversitesi",
    title: "Bakım",
    message: "dhfgkjdhfgkhd",
    // start: new Date(2024, 7, 12, 8, 0),
    // end: new Date(2024, 7, 12, 8, 45),
    // create: new Date(2024, 7, 12, 8, 45),
    start: "30/10/2024",
    end: "30/10/2024",
    create: "10/10/2024",
    allDay: false,
  },
  
];
